### ISSUE TITLE
[Help] 不能连接华为手环7

### ISSUE THREAD

**Issue by Stardust011** [HoshinoSuzumi/HeartBeatMonitor#13]
我已经在手环上打开了心率广播，并且可被手机上的Pulsoid所识别并连接。
无法使用[HeartBeatMonitor][v1.2.2]连接。可被识别，但是卡在正在连接

**Comment by Stardust011** [comment]
v1.2.2

**Comment by HoshinoSuzumi** [comment]
可以尝试重新扫描一次，同时确保手环没有被Pulsoid占用。

我正忙于其他的事情，所以回复得较晚，请谅解

**Comment by Stardust011** [comment]
感谢你的回复。问题已解决。
